USE db_escola;
CREATE TABLE tb_alunos(
id BIGINT AUTO_INCREMENT,
nome VARCHAR (255) NOT NULL,
matricula INT,
materia VARCHAR (255) NOT NULL,
professor VARCHAR (255) NOT NULL,
nota DECIMAL (6,2) NOT NULL,
PRIMARY KEY (id)
);