USE e_commerce;
CREATE TABLE tb_produtos(
id BIGINT AUTO_INCREMENT,
nome VARCHAR (255) NOT NULL,
quantidade INT,
tamanho VARCHAR (255) NOT NULL,
cor VARCHAR (255) NOT NULL,
preco DECIMAL (6,2) NOT NULL,
PRIMARY KEY (id)
);
